### ISSUE TITLE
PFS MatrixListener does not respect `development-environment` and `known_servers`

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-services#1023]
## Problem Definition

A PFS started with `--development-environment demo` and/or configured `known_servers` (a configuration within an RSB deployment) will still fall back to the default `"unstable"` set of `DEFAULT_MATRIX_KNOWN_SERVERS[Environment.DEVELOPMENT]`

See:

https://github.com/raiden-network/raiden-services/blob/08c39cf306c3dd93710843c70a726a9e7a133e09/src/raiden_libs/matrix.py#L279-L294

## Actual Outcome
For the above reasons,  PFS will connect to the pre configured set of servers when tracking presences within the `MultiClientUserAddressManager`.

## Expected Outcome
PFS should respect the configuration options and allow for well defined and restricted deployment environments. That is particularly important for test deployments as well as for third party derived deployments.

**Comment by ezdac** [comment]
But isn't the `matrix-server` CLI arg [set in the RSB](https://github.com/raiden-network/raiden-service-bundle/blob/820c9e5e684c68481002572cd98a97d94ad03702/docker-compose.yml#L42-L44):


https://github.com/raiden-network/raiden-services/blob/08c39cf306c3dd93710843c70a726a9e7a133e09/src/pathfinding_service/cli.py#L71

Which will overwrite the "known_servers" defaults:

 https://github.com/raiden-network/raiden-services/blob/08c39cf306c3dd93710843c70a726a9e7a133e09/src/raiden_libs/matrix.py#L301-L302
