### ISSUE TITLE
Unify logging

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#108]
## Problem Definition

Currently we use the standard lib `logging` and `structlog` for different parts. We should decide on one tool and use it consistently. (keep dependencies in mind, the imported matrix stuff uses structlog)

## Tasks
- [x] Decide on whether `logging` or `structlog`
- [x] Port all subprojects to the decided logging lib.

**Comment by karlb** [comment]
Testing structlog for logging with `pytest.caplog` does not work. Use `pytest.capsys` or https://github.com/wimglenn/pytest-structlog, instead.

**Comment by palango** [comment]
Good point, I|ll have to fix this.
