### ISSUE TITLE
E2E integration/testing scenarios

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden-services#13]
MS should contain multiple tests that verify the whole transport -> MS core -> blockchain path.

What should be tested:
- [x] happy path - all works as expected
- [x] invalid MonitorRequest message
  - [x] client submits MR for a closed channel (is currently accepted and ignored after that)
  - [x] MR with invalid fields (nonce, chain_id and signature tested in `request_collector/test_server.py`)
  - [x] MR with an insufficient deposit in MSC (tested in `test_action_monitoring_triggered_event_handler_with_insufficient_reward_amount_does_not_trigger_monitor_cal`l)
- ~~multiple MSs performing update~~
- ~~client/MS updateTransfer collision~~

**Comment by karlb** [comment]
> client/MS updateTransfer collision

Doing a `transact` won't raise an Exception. The transaction will be checked later and if it failed an error is logged. Not much more we can do in that case.

> multiple MSs performing update

For now it will be the same case as above. In the future we want to make MSs to submit their updates at different times, but this is out of the scope of this ticket.
