### ISSUE TITLE
Call monitor only when MR is from non closing signer

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#136]
## Problem Definition

Currently `monitor` is always called when a channel is closed and we have a MR in the DB. However, this should only be done if the MR is by the non-closing participant.

https://github.com/raiden-network/raiden-services/blob/master/src/monitoring_service/handlers.py#L359

**Comment by karlb** [comment]
We already use `non_closing_signer` to fetch the MR. If the MR is not by the non-closing participant, `None` is returned from the db and we correctly do nothing. So I think the only todo here is to remove the comment.
