### ISSUE TITLE
Get contract addresses from contract package

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#153]
## Problem Definition

Currently the MS and RC need the contracts to be defined in the CLI. The contract addresses should be (and are) defined in the raiden-contracts package. We should take them from there by default but let them be overridden.

- [ ] Get contract addresses for service onctract from `raiden-contracts`  package by default.
- [ ] Let them be overridden by user

**Comment by karlb** [comment]
@pirapira As recently discussed, it would be helpful to get the address for deployed contracts of a specific version programmatically from the `raiden_contracts` package. Should we get it directly from `raiden_contracts/data_{VERSION}/deployment_{TESTNET}.json` or will there be a nicer way to do that, soon? Does https://github.com/raiden-network/raiden-contracts/pull/701 help in that regard?

**Comment by pirapira** [comment]
The API for this is currently like:

```
    deployed_services = get_contracts_deployed(int(web3.version.network), services=True)
    MONITORING_SERVICE_ADDRESS = deployed_services['contracts'][CONTRACT_MONITORING_SERVICE].address
```

**Comment by pirapira** [comment]
By the way, to me the name `get_contracts_deployed` is [terrible](https://github.com/raiden-network/raiden-contracts/issues/671).  So I'll implement any reasonable suggestion.

**Comment by palango** [comment]
There|s also some code in the PFS already:
https://github.com/raiden-network/raiden-services/blob/master/src/pathfinding_service/cli.py#L44-L56
