### ISSUE TITLE
Draft Planning Q2 Raiden Services 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#165]
# Focus on 5 objectives in Q2 2019:
" In Q2 we should deploy a stable main net release"

- Testing
- Routing
- Missing Features
- Infrastructure
- (Long term) Research

## Some notes to clarify

- Missing features (in order of importance):
  - Integrate mediation fees into PFS
  - Persistence of PFS (DB integration)
  - Routing in general (client, source routing, presence check, reputation system/routing success evaluation)
  - PFS helps with peer discovery
  - MS provides price feedback
- Deployment / DevOps
  - Monitoring of services/statistics
  - Easy install of services 
- Research topics
  - Routing in general (w/ respect to competitors)
  - Routing feedback gathering
  - Full node dependency
  - Other monitoring services approaches
  - Lightning
  - Hire a master student?!
- Technical debt
  - Get rid of Raiden dependency library

**Comment by Dominik1999** [comment]
![Raiden-PlanningQ2-Whiteboard-Notes](https://user-images.githubusercontent.com/35031754/54282249-e1ad7700-459b-11e9-9db0-cfcdb2cb7297.jpg)

**Comment by Dominik1999** [comment]
@palango @karlb please edit in case you understood anything differently

**Comment by palango** [comment]
Done as of today.
