### ISSUE TITLE
Better retrying of web3 requests

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#19]
Use the same solution as in the PFS: https://github.com/raiden-network/raiden-pathfinding-service/commit/4a2eee82df4b78699c81301e81924e905beb9530. Move the middleware and the test for it to a shared place and use it in both projects.

**Comment by Dominik1999** [comment]
Do we have a shared place for the path finding and the monitoring service already? Or is that what @palango is currently working on?

**Comment by palango** [comment]
Fixed by #206
