### ISSUE TITLE
Proper fee calculation for route

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#235]
Currently we simply add all channel fees together. Depending on the fee model this might or might not be correct (e.g. percentage fees):
```py
            for node1, node2 in zip(path[:-1], path[1:]):
                fee += self.G[node1][node2]['view'].relative_fee
```

Check that the calculation is valid for the current fee model.

**Comment by karlb** [comment]
Superseded by https://github.com/raiden-network/raiden-services/issues/368.
