### ISSUE TITLE
Do contract calls on unconfirmed blocks

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#239]
Currently we do calls to contracts (like the deposit of a user in the UDC) based on the latest block.

Instead we should take the lowest of all blocks from the last confirmed until the latest block.

**Comment by karlb** [comment]
For the PFS this is safe, but will force a user to wait until confirmation of his deposit before he can start using a PFS.

For the MS, using unconfimed blocks opens an attack vector. If an attacker can manipulate a single block, a MS can be misled regarding the UDC deposit and will not monitor properly. On the other hand we must make sure that MSs can't be abused to close channels for free.
