### ISSUE TITLE
Research Routing Approaches

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#272]
## Description

We want to know what our competitors do regarding their routing. So we need to research about how routing is executed in 
- [x] Lightning Routing
- [x] Celer Network Routing
- [x] (insert most interesting third competitor)

The end result will be a short booklet about different routing approaches and how we compare to that.

**Comment by karlb** [comment]
https://crysp.uwaterloo.ca/software/speedymurmurs/ also looks interesting, although it's no competitor.

**Comment by palango** [comment]
@Dominik1999 Do you still have the link the the blogpost about lightning routing you sent me once?

**Comment by Dominik1999** [comment]
sure

**Comment by mat7ias** [comment]
Collected some resources on this if it helps: 

**Lightning**
- [Trampoline routing](https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-April/001956.html)
- [Rendez-vous routing](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-November/001498.html)
- [Just in Time Routing (JIT-Routing) and a channel rebalancing heuristic as an add on for improved routing success in BOLT 1.0](https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-March/001891.html) 
- [Rebalance Plugin for JIT Routing](https://github.com/renepickhardt/c-lightning-plugin-collection/tree/master/rebalance-jit-routing)

**Celer Network** 
- Distributed Balanced Routing - [Whitepaper](https://www.celer.network/doc/CelerNetwork-Whitepaper.pdf) ("cRoute")

**Connext**
- [Threads](https://connext.readthedocs.io/en/latest/develop/contracts.html#threads), similar to Perun Virtual Channels.

**Comment by Dominik1999** [comment]
Thank you @mat7ias! I will look into it. cRoute sounds very interesting to me, but afaik not quite possible when using HTL.

**Comment by Dominik1999** [comment]
closing for now
