### ISSUE TITLE
Reduce Technical Debt in Services 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#274]
## Description

We want to reduce our technical debt in order to achieve a more efficient working process. We identified two specif issues:

- Include tests for matrix integration to achieve a higher test coverage #124 
- Compare pylint settings and align with other teams #280 

## Acceptance Criteria

- [x] Cover matrix integration with unit tests, see issue #124
- [x] Agreed pylint standard x-teams
- [x] #286 
- [x] #289
- [x] Get test coverage above 90%

**Comment by karlb** [comment]
> Compare pylint settings and align with other teams

I'd rather try "enable as much as reasonably possible" in each project. Alignment does not bring much benefit in this case and will probably hold bad stricter checks.

**Comment by karlb** [comment]
> Agreed pylint standard x-teams

With the exceptions listed in https://github.com/raiden-network/raiden-services/issues/280#issuecomment-487515244, we have enable all pylint checks that are enabled in raiden. So I'll check this checkbox.
