### ISSUE TITLE
Routing is reasonable successful

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#276]
## Description

We need to measure and improve the pfs to a high success rate of the provied routes. 

## Acceptance Criteria

- [ ] Define successrate 
- [ ] Monitor success rate, (realate #275 )
- [ ] Define test scenarios to show success rate

**Comment by palango** [comment]
Some metric proposed in the paper *Settling Payment Fast and Private: Efficient Decentralized Routing for Path-Based Transactions*:

- **Effectiveness**: Fraction of successfully resolved transactions
- **Efficiency**: Delays experienced during a transaction and overhead created by transactions
- **Scalability**: Ability of a network to maintain effectiveness and efficiency for a growing base of users and transactions.
