### ISSUE TITLE
Handle MS crashes while processing a block

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#32]
If no special precautions are taken, some events might be handled zero or multiple times after restarting the MS.

Split off from #17.

Related to #63 

8 SP

**Comment by hackaugusto** [comment]
This may be of interest: https://github.com/raiden-network/raiden/blob/ab4784b975cb8a93daeccc4266e7a3aabc587f07/raiden/raiden_service.py#L559-L573
