### ISSUE TITLE
Use byte encoded addresses

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#325]
In contrast to Raiden we use hex-encoded addresses. This complicated interoperability and is source of confusion.

We should switch to use byte-encoded addresses internally.

**Comment by karlb** [comment]
There's also the HexBytes type which behaves like bytes but provides a hex representation when printed. Do we want to use this or not?

**Comment by palango** [comment]
> There's also the HexBytes type which behaves like bytes but provides a hex representation when printed. 

With the advantage being that we wouldn't need to encode all byte-addresses, e.g. for logging?!

But I guess we would need to create the objects ourselves, so wouldn't this lead to the same inconsistencies like we have now?

**Comment by karlb** [comment]
We should probably talk about this with someone from the client team to make sure that we're going into the right direction. See https://github.com/raiden-network/raiden/issues/3051.

@andrevmatos: any comments on this?

**Comment by andrevmatos** [comment]
The decision to use byte-encoded was made long ago on Raiden client, and checksummed-hex-encoded on all REST/HTTP interfaces and JSON communcation (like Matrix), so I'd say services would do good in keeping this pattern as well. `web3.py` initially supported only hex-encoded strings, but some time ago also added full support to bytes addresses everywhere.
The `HexBytes` is just some logging sugar, while my proposal in 3051 Karl pointed above has some more additional fancyness, while keeping full inheritance with `bytes`, so I think it'd be nice if anyone is willing to finish or import the work from there, it could be useful while being transparently handed over to Raiden and libs.
