### ISSUE TITLE
Specify and implement MR-Messages for raiden client

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#34]
- [x] specify message format
- [x] get massage format accepted by client team
- [x] generate message on the client (actual sending will be done in [#3273](https://github.com/raiden-network/raiden/issues/3273))
- [ ] deserialize message on MS (actual matrix listening will be done in #14) 

Relies on Raiden issue

8 SP

**Comment by Dominik1999** [comment]
- to check, when UDC needs to query participant data from TokenNetwork Contact (data might be erased after settle)

**Comment by Dominik1999** [comment]
- how and when will the user send an MR - todo define "User Policy"

**Comment by Dominik1999** [comment]
@konradkonrad will take up this issue (specific client issue #3273, see above)

**Comment by palango** [comment]
The MS will use the Raiden message for decoding as well. Remaining work will be tracked in #14
