### ISSUE TITLE
Spec out Mediation Fees communication between client and PFS

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#341]
- [x] Read up on previous mediation fees discussions:
  - [x] https://github.com/raiden-network/spec/issues/10
  - [x] https://github.com/raiden-network/team/issues/225
- [x] Talk to trustlines about their imbalance fees
- [x] Discuss with client team
- [x] Write ADR

**Comment by karlb** [comment]
Results for older discussions:
* Mediation fees are paid in the token that is being transferred
* Mediation fees can not be set globally. They have to be set either per token network or per channel.

General points regarding general mediation fees:
* Mediation fees will not be enforced for now. If we add onion routing, that can and should be used to enforce mediation fees.

General points regarding the imbalance fees:
* Imbalance fees don't work for nodes which are only sources of tokens or sinks. For those, `deposit` and `withdraw` will have to be used to regain capacity.
* Imbalance fees should depend on the transferred amount. Otherwise you can't even tell if the channel is getting more or less balanced.
* It depends on the node which state is desired (and thus considered "balanced"). Clients which mostly use their channel to pay will want as much free capacity as possible, while mediating nodes might want the capacity evenly split between both parties to facilitate mediations in both directions.
* Imbalance fees should grow non-linearly with the transferred amount to disincentivize fully exhausting a channel.
* For the network balance, it's not only relevant over which channel a mediating node sends a payment but also over which channel the payment is received. For optimal balancing results, it is necessary to include this information in the overall mediation fee.

**Comment by karlb** [comment]
To evaluate different approaches, let's go through some basic examples and rate which transfers are desirable for a node. Then we can evaluate which imbalance fees can be used to properly express the node's intention. Plus signs show desired transfers, minus signs those which are to be avoided.

Example 1:

A mediating node has three channels. The channel to C is nearly exhausted, while the other channels have a free capacity of 9 tokens left (of 10 tokens which are deposited in that channel). This node wants to have 
a similar amount of free capacity for all channel, so that it has more mediation opportunities. To achieve this, it must receive tokens over channel C.

| from\to | A | B | C |
| --- | --- | --- | --- |
| A 1/10 | | - | -- |
| B 1/10 | - | | -- |
| C 9/10 | ++ | ++ | |

Example 2:

A customer uses channel A only to pay and therefore would like to mediate in the reverse direction.

| from\to | A | B |
| --- | --- | --- |
| A 5/10 | | -- |
| B 5/10 | ++ | |

@Dominik1999 @palango @hackaugusto: Are those tables readable to you? Any suggestions for good corner cases?

**Comment by Dominik1999** [comment]
I could not find any more corner cases. So Let's start with these two and see what the future brings ...

**Comment by palango** [comment]
> A customer uses channel A only to pay and therefore would like to mediate in the reverse direction.

Either I don't get the example or the pluses and minus are switched. The node want all token on its side of the channel, so a transfer from B -> A makes stuff worse, but a transfer A -> B improves the balance.

**Comment by Dominik1999** [comment]
Interesting read / impuls https://www.scribd.com/document/401282988/Routing-Fee-Proposal

**Comment by karlb** [comment]
We agreed on a solution. I'll start writing a proper ADR with the results.
