### ISSUE TITLE
Specify 1-n payment solution

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#35]
- [x] Discuss 1-n payment options
- [x] Decide on details of preferred solution
- [x] Add specification to raiden spec repo

Suggestions so far raiden-network/team#257 and https://gist.github.com/heikoheiko/214dbbd954e0f97e0e13b2fefdc7c753

13 SP

**Comment by karlb** [comment]
First draft at https://github.com/raiden-network/raiden-services/issues/38.

**Comment by palango** [comment]
@karlb Can we close this?
