### ISSUE TITLE
Problems decoding keyfile

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#359]
In our deployment sometimes the servcies cannot decode the keyfiles:

```
msrc-goerli_1           | 2019-05-16 14:52.03 Could not decode keyfile with given password. Please try again. reason=Error 2 while running scrypt
```

**Comment by palango** [comment]
According to https://github.com/Legrandin/pycryptodome/issues/85 this happens if not enough memory is available.

So we need to upgrade the server.

**Comment by palango** [comment]
@nlsdfnbch @ulope Can we increase the RAM of the droplet from 2GB to 4GB?

**Comment by nlsdfnbch** [comment]
Resized successfully and droplet spun up again. 

Please check everything is working as expected, @palango 
```
services-dev.raiden.network
in Raiden Network / 4 GB Memory / 60 GB Disk
```

**Comment by palango** [comment]
Restarted everything and saw now such errors.
