### ISSUE TITLE
https://ms-goerli.services-dev.raiden.network not working

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-services#381]
Currently the MS scenarios fail, because the MS is not working:

```
$ http https://ms-goerli.services-dev.raiden.network            

http: error: SSLError: HTTPSConnectionPool(host='ms-goerli.services-dev.raiden.network', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))) while doing GET request to URL: https://ms-goerli.services-dev.raiden.network/
```

**Comment by palango** [comment]
@nlsdfnbch Any idea how this can be fixed?

**Comment by czepluch** [comment]
Haha. The circle is complete. Started with asking Nils, he suggested to ask Ulo, Ulo suggested asking the services guys.

**Comment by ulope** [comment]
Haha, I'll take a look

**Comment by palango** [comment]
Mh, but the MS doesn't have any HTTP interface.

**Comment by ulope** [comment]
Yeah I was just noticing that the `ms-*` services aren't enabled in traefik.

**Comment by palango** [comment]
@czepluch Can we close this as this isn't supposed to work or do you expect something else?
