### ISSUE TITLE
Deployment guide

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#408]
We need better docs for *Configuration and instructions for running Raiden Services*

A good example is the transport repo: https://github.com/raiden-network/raiden-transport/

**Comment by karlb** [comment]
Is this a duplicate of https://github.com/raiden-network/raiden-services/issues/402, or do we need two separate guides for some reason?

**Comment by palango** [comment]
> do we need two separate guides for some reason?

Isn't 3 the magic number?
