### ISSUE TITLE
Request collector crashes on unsigned RequestMonitoring Messages

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#420]
A server hosting the request collector can be crashed with different malicious messages, e.g.

- `request_monitoring.non_closing_signature = None` causes an assertion error,

- `request_monitoring.balance_proof.token_network_address = b'\0' * 2147483647` causes a memory error

once `handle_message` is called.

**Comment by karlb** [comment]
> `request_monitoring.balance_proof.token_network_address = b'\0' * 2147483647` causes a memory error

This will be caught by `ValueError: Unknown format` if it does not exceed the memory. The memory could be a more general problem. If we don't limit the incoming JSON size in some way, our memory can be drained just by constructing large JSON messages, no matter what the content is. Do we already have anything limiting the message sizes (e.g. size limits in the matrix transport)? @err508

**Comment by err508** [comment]
No, we face the same problem in matrix. I'd not rely on the the transport to sanitize the messages for the MS though, however you can open an issue for matrix, we'll probably solve the problem after moving to matrix-nio and could let u know if we have something reusable.

**Comment by ulope** [comment]
Regarding 2. we kind of have the inverse problem in the client: https://github.com/raiden-network/raiden/issues/3512

Matrix servers reject events that are bigger than 65k, that means the actual message data will be slightly smaller than that. 

Of course it doesn't hurt to have an additional check in place to guard against bugs or maliciously modified servers.

**Comment by Dominik1999** [comment]
Thank you @ulope 
according to that https://stackoverflow.com/questions/17574076/what-is-the-difference-between-len-and-sys-getsizeof-methods-in-python

sys.getsyzeof() returns the size of the object in the memory, right? So it would be the correct function to use?
