### ISSUE TITLE
Monitoring Service sends unsanitized onchain transactions

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#421]
The attacker crafts a MonitoringRequest which violates one of the contract's constraints but none of the MonitoringService's constraints (e.g. `non_closing_signer == reward_proof_signer`). The MonitoringService will send a transaction and burn gas.

**Comment by karlb** [comment]
I suggest to avoid this problem by doing a `call` and only execute the `transact` if the `call` succeeds.

Pros:
* Simple
* Uses exactly the same code path

Cons:
* Can only be executed immediately before the `transact`. Weeding out bad MonitoringRequests early does not work.

**Comment by palango** [comment]
The client uses `estimateGas` for that. Some more infos about the whole transaction pre/post conditions in the client are here: https://hackmd.io/9RJdZJkPQmuUFVy_yBUdGw


For the disadvantage: For knowing in advance if the MR will work we would need to copy the channel state, close it and try the MR, right? I see no way of doing this without the private keys.

**Comment by karlb** [comment]
> For the disadvantage: For knowing in advance if the MR will work we would need to copy the channel state, close it and try the MR, right? I see no way of doing this without the private keys.

Yes, and and the timing checks will also prevent early calls. So I really don't see a reasonable way to avoid that disadvantage when choosing this approach. But the pros seem good enough to accept that.

**Comment by palango** [comment]
Ok, let's go with the `call`/`estimateGas` version then.

**Comment by karlb** [comment]
We're already implicitly using `estimateGas` when doing the `transact`. All errors are also caught and logged. So this attack seems to be handled, already.

The only thing that's lacking is the detail of error messages we get when `estimateGas` fails. Instead of adding more checks in the python code, I would prefer to add messages to all `requires` in the `MonitoringService` contract (see https://github.com/raiden-network/raiden-contracts/issues/1111).

**Comment by palango** [comment]
>  I would prefer to add messages to all requires in the MonitoringService contract

Are those handled by `web3.py` now?

**Comment by karlb** [comment]
According to @pirapira, web3 does handle the require messages, now.

**Comment by pirapira** [comment]
because `pytest` shows me the error messages.

**Comment by pirapira** [comment]
(regarding https://github.com/raiden-network/raiden-contracts/issues/1111, I'm in the course of adding the messages right now.)
