### ISSUE TITLE
PFS receives and processes balance updates from clients

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#48]
## Description

**As Josh I want to be able to**

get balance proof updates published by the clients processed by the path finding service.

**So that I can**

get a route I can use with high likelihood at the first try.

## Acceptance Criteria

- [x] path finding service listens to the global matrix room for balance proof updates
- [x] path finding service stores and processes all balance proof updates 
- [x] path finding service includes current balances and reveal_timeouts into routing algorithm

## Related story / issue
- [Client publish balance updates to pathfinding service](https://github.com/raiden-network/raiden/issues/3364)
- #47 

**20 SP**

**Comment by Dominik1999** [comment]
We decided that instead of balance proofs the client should sent a signed message containing the current free capacity on both channel sides. This message can also be signed and a nonce can be added. 

The reasoning behind it: With only one balance proof we cannot calculate the current balance in the channel and we can not ensure that we get both balance proofs from every side.

**Comment by Dominik1999** [comment]
closed by #175

**Comment by palango** [comment]
Mh, we still need to update the message and see that it works, I wouldn't close this yet.
