### ISSUE TITLE
Avoid race condition between MSes

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#505]
Currently, a MS will not see that another MS has called `monitor` until that event is confirmed. That might lead to multiple MSes to expend gas on calling `monitor`.

Instead, the MS should listen to unconfirmed events. If an unconfirmed `NewBalanceProofReceived` event is seen, the MS should wait until that event is confirmed or discarded.

**Comment by karlb** [comment]
The MS will notice this before wasting gas because the gas estimation fails. So I'm not sure we actually want to do anything, here.

**Comment by palango** [comment]
> The MS will notice this before wasting gas because the gas estimation fails. So I'm not sure we actually want to do anything, here.

There are still race conditions, right? If I run the gas estimation on a block that doesn't have the successful update in it it will go through.

**Comment by karlb** [comment]
> There are still race conditions, right? If I run the gas estimation on a block that doesn't have the successful update in it it will go through.

Isn't the gas estimation run on the latest block? If it is, is there anything better we could do than checking the latest block by doing a gas estimation?

**Comment by palango** [comment]
I don't see a better way, closing.
