### ISSUE TITLE
I want to be able to log via network

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden-services#518]
## Description
As a use I want to be able to optionally configure a log handler on service startup, that sends logs to a specified `netloc` using the python `logging` library, in addition to logging to a local file.

## Acceptance Criteria

- [ ] I can pass `--log-service 127.0.0.1:5055` to the service CLI, and a pthon `logging` server running on that address receives the services log output.
- [ ] Not passing the option does not send any logs via network.

## Related story / issue
- https://github.com/raiden-network/scenario-player/issues/59

**Comment by palango** [comment]
As far as I know we opt for a different solution now.
