### ISSUE TITLE
Update to python 3.7

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#53]
## Problem Definition

Raiden recently switched to python 3.7, we should do the same. Problem is that travis currently doesn't support python 3.7, so we might have to switch to CircleCI.

https://github.com/raiden-network/raiden-services/pull/49#pullrequestreview-198501783

**Comment by LefterisJP** [comment]
@palango We are using python 3.7 in rotkehlchen for both OSX and Linux tests. Here is the travis.yml: https://github.com/rotkehlchenio/rotkehlchen/blob/a5ed53d095d2531da7a7ff158f7c68deef3a280c/.travis.yml

**Comment by palango** [comment]
@LefterisJP Nice, thanks for the link!
