### ISSUE TITLE
Introduce an API endpoint to query the estimated transfer mediation fee

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden-services#531]
## Description

To provide user with information on what the cost of the transfer is, the PFS should provide an endpoint similar to the "route query" endpoint, which only returns the estimated fee value (possibly, min and max values).

## Acceptance Criteria

- [ ] TBD

## Related story / issue
- https://github.com/raiden-network/raiden/issues/4771

**Comment by karlb** [comment]
Fee estimates are included with the routes in the same response.
