### ISSUE TITLE
More specific error when sender or receiver are offline

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#542]
Currently in that case only a `No route found` is shown, which irritates people.

**Comment by karlb** [comment]
The case where the sender is offline is a strange one. Did anyone manage to get that?

**Comment by palango** [comment]
On Friday Jacob showed me some logs where this happened. But you're right, this should never happen.

**Comment by palango** [comment]
Fixed by ab6a62525adce918d555650bf8c201705fba78b1
