### ISSUE TITLE
PFS route request performance

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#550]
It seems like sometimes the PFS needs to long to reply to route requests (@Dominik1999 )

We should try to replicate this scenario, measure performance and then improve it.

**Comment by karlb** [comment]
https://gist.github.com/Dominik1999/81eb66525d57ba5b902b88f04123af74 works for me and uses the PFS for routes until the end. Route requests take 0.2-0.3s, which is slow considering the tiny network, but should not lead to any timeouts.

**Comment by Dominik1999** [comment]
ok then let's close this issue
