### ISSUE TITLE
Improve MSC event filtering topics

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#56]
## Problem Definition
In PR #55 event listening for the MS contract was added: https://github.com/raiden-network/raiden-services/pull/55/files#diff-71a32fe34ce65673e1568513af4c609bR43

We need to investigate if we can use better filter topics, as we're only interested in events for our updates.

**Comment by Dominik1999** [comment]
Result: we can not enhance filtering by listing other topics. There are two events emitted by the contract and the monitoring service needs to listen to both of them and all the data included to decide whether or not to accept a Monitoring Request
