### ISSUE TITLE
Add as many iterations into PFS imbalance fee calculation as we use in the Raiden client

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#563]
Currently, the Raiden client iterates the imbalance fee calculation one time whereas the corresponding calculation in the pfs does not iterate.

We need to adjust the pfs fee calculation to the client calculation.

See here for reference https://docs.google.com/spreadsheets/d/1nHVCOhMcrM-L8brJj_C_Qb0Paws1qwozcNHU3VFcWEY/edit#gid=1257400215

**Comment by palango** [comment]
There is some code for this in https://github.com/raiden-network/raiden/pull/5024, this needs to be copied to the PFS or be used from the raiden codebase.
