### ISSUE TITLE
Replace user timestamps with block number + confirmation interval

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-services#572]
## Problem Definition

`handle_channel_fee_update(...)`, https://github.com/raiden-network/raiden-services/blob/9acfd0e374f0b1aabd21d3f1c22c17410b7fca1f/src/pathfinding_service/model/token_network.py#L292-L295 has logic for checking a user provided wall-time timestamp against the server wall time.

According to what I understood, this is done in order to avoid synchronization issues if client and service use different confirmation intervals.

Since client timestamps are highly error prone, I would suggest to change this logic. I propose to refer to the blockchain's block numbers as the only time source. 

In order to handle cases with differing confirmation intervals, clients should include their current block number + their configured confirmation interval when they send their fee updates.

Example:
```python
PFSFeeUpdate(
  canonical_identifier: ...,
  updating_participant: ...,
  fee_schedule: ...,
  timestamp: "50034+8"
)
```
would encode that the client created the fee update at block `50034` with a configured confirmation interval of `8`.

**Comment by karlb** [comment]
The client could send multiple updates during the same block in which case the order would be ambiguous. Or can we rely on any ordering guarantees made by the transport?

**Comment by karlb** [comment]
With the arbitrum-related switch to timestamps instead of blocks, changing this would not make sense anymore.
