### ISSUE TITLE
Service Providers README.md

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/raiden-services#580]
## Problem Definition
I tried to find if this issue is contained within a larger issue already worked on. Currently the [Service Providers README.md](https://github.com/raiden-network/raiden-services#service-providers) links to "[service provider README](https://github.com/raiden-network/raiden-services/blob/master/package/README.md)".

## Actual Outcome
Page not found.

## Expected Outcome
Something similar, or a replacement of, the service provider README [previously linked](https://github.com/raiden-network/raiden-services/blob/new_release_2000/package/README.md).

**Comment by palango** [comment]
Let's wait until https://github.com/raiden-network/raiden-transport/issues/34 is done, otherwise we have to do this again.
