### ISSUE TITLE
Change the URL for deployment of PFS to include its version

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden-services#613]
## Description

**As Josh I want to be able to**

Have unique URLs for the services, depending on their version

**So that I can** 

setup the Raiden Wizard with a URL for PFS that will not change.

## Acceptance Criteria

- PFS is available on a URL scheme that includes information about its version, e.g, "https://pfs.goerli.services.raiden.network/vX.Y"

## Related story / issue
https://github.com/raiden-network/team/issues/663

**Comment by palango** [comment]
I don't find the relevant issue right now, but we currently provide testnet services for the latest (unstable) release and latest master.

We don't have plans to provide all versions of the services for the testnets.

**Comment by lullis** [comment]
@palango, this change was already discussed yesterday and it is needed for us to have a consistency set of components for those running raiden with the configuration generated by the Wizard.

To illustrate, take a look at https://github.com/raiden-network/raiden-installer/issues/72. The fact there was an upgrade on the PFS broke all of the installations done via the Wizard. Having the version of the PFS on the URL avoids that.

**Comment by lullis** [comment]
https://github.com/raiden-network/raiden/issues/5187 should give you a basic history of what is the plan, with the added information that yesterday the reached conclusion was that, given that raiden services depends on more than the contract version to determine compatibility, it will be better if the service itself indicates which version it is in the URL.

>  Why complicate stuff with version numbers?

We want to simplify actually. Numbers are stable. Consumers of the services should not need to worry about what to expect when they connect to a service, and the developers of the service should not worry if their deployment of version X will affect users of version X - 1.

**Comment by palango** [comment]
According to my current understanding we won't do this. We can reopen if the plan changes.
