### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#620]
## Problem Definition

@kelsos triggered another problem with deserialization

https://sentry.io/organizations/raiden-network/issues/1321013291/?project=1509055&referrer=alert_email

request data:
```json
{"from": "0x2046F7341f15D0211ca1EBeFb19d029c4Bc4c4e7", "iou": {"amount": {"_hex": "0x64"}, "chain_id": {"_hex": "0x05"}, "expiration_block": {"_hex": "0x188c00"}, "one_to_n_address": "0x0000000000000000000000000000000000000000", "receiver": "0x94DEe8e391410A9ebbA791B187df2d993212c849", "sender": "0x2046F7341f15D0211ca1EBeFb19d029c4Bc4c4e7", "signature": "0x8bb8377941dcd57301bbf0d392164dc965e7d57f059c01afca659592b89965742cddd362db4a2505fab5796487d5985c2c58bb8b4ba845c4de85cadc1c9fd6151b"}, "max_paths": 10, "to": "0xc52952Ebad56f2c5E5b42bb881481Ae27D036475", "value": 1000000000000}
```

## Actual Outcome

Crashes the PFS

## Expected Outcome

Should be handled nicely

**Comment by kelsos** [comment]
I am just randomly trying messages until it works :P

**Comment by LefterisJP** [comment]
Generally both here and in Raiden we should use the marshmallow validation for all fields. This way all input that goes into the core will be validated and won't cause unexpected crashes.

**Comment by palango** [comment]
The problem is that somehow https://github.com/raiden-network/raiden/blob/b324b7bd7256f64ad6662ad9a4695a07135bcb7f/raiden/storage/serialization/fields.py#L14-L19 gets used, which doesn't have proper validation and error handling.

**Comment by karlb** [comment]
@kelsos: You are sending `{"_hex": "0x64"}` instead of integers for `iou`, `chain_id` and `expiration_block`. The request won't work until you change that.

```json
{"from": "0x2046F7341f15D0211ca1EBeFb19d029c4Bc4c4e7",
 "iou": {"amount": {"_hex": "0x64"},
 "chain_id": {"_hex": "0x05"},
 "expiration_block": {"_hex": "0x188cba"},
 "one_to_n_address": "0x0000000000000000000000000000000000000000", "receiver": "0x94DEe8e391410A9ebbA791B187df2d993212c849", "sender": "0x2046F7341f15D0211ca1EBeFb19d029c4Bc4c4e7", "signature": "0x0c3066e6a954d660028695f96dfe88cabaf0bc8a385e51781ac4d21003d0b6cd7a8b2a1134115845655d1a509061f48459cd401565b5df7845c913ed329cd2351b"}, "max_paths": 10, "to": "0xc52952Ebad56f2c5E5b42bb881481Ae27D036475", "value": 0}
```

But we should send a validation error, of course.

**Comment by kelsos** [comment]
@karlb Yes, it has been already fixed on my side :+1:

**Comment by karlb** [comment]
I'm trying to solve this by improving the marshmallow fields defined in Raiden: https://github.com/raiden-network/raiden/pull/5269
