### ISSUE TITLE
PFS performance - Investigate performance of 'matrix_listener.follow_address_presence'

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#644]
Seems like we unnecessarily call `matrix_listener.follow_address_presence` with the `refresh=True` parameter, which hurts performance.

It also seems like the call is blocking, whereas it should be non-blocking.

- [x] do simple thing - remove two (maybe four) lines 335 [SP 2]
- [ ] do elaborate thing - remove and optimize all remaining occurrences [SP 8]

**Comment by karlb** [comment]
We've changed the presence handling a lot since this ticket has been filed. I assume it is stale.
