### ISSUE TITLE
Add APIs for healtchchecking the services

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden-services#650]
## Problem Definition

Both the MS and the PFS must have healtcheck APIs for proper provisioning checks.

**Comment by karlb** [comment]
How should such a thing look for the MS, which does not really have an API? Updating a file with a timestamp to show that it's still alive?

**Comment by hackaugusto** [comment]
> How should such a thing look for the MS, which does not really have an API? Updating a file with a timestamp to show that it's still alive?

Just add an endpoint `/health` that return a valid response if the system is properly initialized. Having a simple HTTP interface makes it easier to integrate with existing DevOps tools

**Comment by karlb** [comment]
https://github.com/raiden-network/raiden-services/issues/763 is more detailed.
