### ISSUE TITLE
Improve PFS Performance - Optimize blockchain polling

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#672]
Optimize `event_abi_to_log_topic` because 5.77% of the time is spent here.
  - Moved to https://github.com/raiden-network/raiden-services/issues/794
We might save up to ~40% of the time by batching of event polling.

First:

- [x] finalize https://github.com/raiden-network/raiden/pull/5003 in Raiden
- [ ] batch event polling like in Raiden here https://github.com/raiden-network/raiden/pull/5003
- [x] combine multiple `get_logs` calls to one

Related to #651

**Comment by palango** [comment]
Further improvements tracked in #793
