### ISSUE TITLE
Wrong/Outdated balances in bf6, despite 100s wait

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#675]
The bf6 scenario fails with `Should: "500000000000000000" Is: "0"` during the step `Assert after balancing channels`, despite having a generous 100s wait before. This is so slow that I suspect there's some kind of bug involved rather than just general slowness. If it is matrix related, it might share a cause with https://github.com/raiden-network/raiden-services/issues/673.

This scenario was run with a local PFS. The log is included in the zip.

**Comment by Dominik1999** [comment]
this is tracked in https://github.com/raiden-network/raiden/issues/5412
