### ISSUE TITLE
Services receive unrelated messages

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#713]
The PFS receives `RequestMonitoring` messages
The MS received PFS messages

### Tasks
- [x] Enable whitelisting of room in `Client`
- [ ] Use whitelisting for only listening to certain rooms

**Comment by palango** [comment]
@ulope @fredo  This is a bit weird, in the MS we're only joining the monitoring broadcast rooms. However, we still get messages that are sent in the PFS room. The same happens to the PFS.

When I check the rooms in riot, I see them in the correct room. This means that we somehow join other rooms (but the MS only calls `join_mbroadcast_room` once).

Do you have any idea what could cause that? Wrong aliases, server-side caching of joined-rooms...

**Comment by ulope** [comment]
@palango Do you by any chance use the same account for both MS and PFS?

**Comment by palango** [comment]
@ulope Yes, they use the same account. So we need to split that? That would make the registration harder, because we assumed that one key can be used for both services.

**Comment by ulope** [comment]
Yes, ideally you'd use two independent accounts.
But you could try setting up [sync filters](https://matrix.org/docs/spec/client_server/r0.6.0#filtering) for each service that only return events from the room(s) you're interested in for the specific service.
