### ISSUE TITLE
In MS Scenarios - No RewardClaimed event found for this channel 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#734]
## Problem Definition 

In [MS1](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/ms1_simple_monitoring.yaml), [MS2](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/ms2_simple_monitoring.yaml) and [BF1](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml) we want to see the Raiden monitoring service to react properly. Monitoring works and the Monitoring Service reacts as expected. 

However, those scenarios fail constantly when the Monitoring Service tries to claim its reward with 

```
ScenarioAssertionError(\"No RewardClaimed event found for this channel.\") scenario_player.exceptions.legacy.ScenarioAssertionError: No RewardClaimed event found for this channel.",
```

The calculation of the point in time at which this reward is to be claimed seems wrong.

**Comment by palango** [comment]
I ran a scenario with additional logging a `call` before calling `transact`: This showed the following information:
```
In [2]: decode_hex("0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000176368616e6e656c206e6f7420736574746c656420796574000000000000000000")
Out[2]: b'\x08\xc3y\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17channel not settled yet\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
