### ISSUE TITLE
Service registration script needs UX improvements

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-services#768]
## Problem Definition

I was helping Florian from KI Decentralized setting up a test installation of the current RSB release.
When running the registration script the following UX issues came up:

- [ ] The prompt [`The address of the service registry contract used is ... / I have checked that the address is correct and want to continue`](https://github.com/raiden-network/raiden-services/blob/bc5e0a8b43cf64ae06c883b551ab8b5804a51f6c/src/raiden_libs/service_registry.py#L209-L214) isn't actionable for the average RSB user. 
  We don't provide any guidance on how they can verify that it is indeed the correct address. 
- [x] [`The address of the token used is ... / The account balance of that token is ...`](https://github.com/raiden-network/raiden-services/blob/bc5e0a8b43cf64ae06c883b551ab8b5804a51f6c/src/raiden_libs/service_registry.py#L218-L225) does neither specify units nor display the name / symbol of the asset in question (Eth, token, etc.) (The same is true for the log call directly above)
- [x] [`The current required deposit is ...`](https://github.com/raiden-network/raiden-services/blob/bc5e0a8b43cf64ae06c883b551ab8b5804a51f6c/src/raiden_libs/service_registry.py#L246) has the same problem. No units, no asset name / symbol.
- [x] [`Note: The required deposit may change over time.`](https://github.com/raiden-network/raiden-services/blob/bc5e0a8b43cf64ae06c883b551ab8b5804a51f6c/src/raiden_libs/service_registry.py#L247) isn't clear. When is "over time" and how can it change?
- [x] The fact that on testnets tokens are automatically minted should be mentioned before the balance and the question whether to perform the registration are shown.
- [x] Even though the balance of the service token is shown there is no check if it's sufficient for the registration.

**Comment by karlb** [comment]
> The prompt The address of the service registry contract used is ... / I have checked that the address is correct and want to continue isn't actionable for the average RSB user.
We don't provide any guidance on how they can verify that it is indeed the correct address.

@ulope Do you have any suggestion what the guidance could be? I have a hard time coming up with anything that is substantially more helpful.

**Comment by ulope** [comment]
Well yeah, I agree that this can be probably not be adequately explained in a few lines in a console script.
But just linking to etherscan isn't helpful either IMO.
Without pretty detailed knowledge how the Raiden smart contracts and our deployment system works I don't think it's possible for an average user to learn anything there.
