### ISSUE TITLE
Internal security audit/pen-testing

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-services#8]
- [x] #44 
- [x] #51 
- [x] check chain id when getting BP or Fee updates
- [x] Independent review from other team member

Problems to fix:
- [x] https://github.com/raiden-network/raiden-services/issues/418
- [x] https://github.com/raiden-network/raiden-services/issues/419
- [x] https://github.com/raiden-network/raiden-services/issues/420
- [x] https://github.com/raiden-network/raiden-services/issues/421

**Comment by palango** [comment]
@err508 We fixed all problems to a degree we feel comfortable with. Whenever you have some spare time feel free to look over the solutions.
