### ISSUE TITLE
Connect to all federation servers to fetch correct presences

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden-services#897]
This was the idea of @fredo:

To avoid the presence problem, a node could connect to all possible Matrix federation servers
in order to gather the correct presences for all users in the broadcast room, in order to avoid the presence sync problem 
across federation servers.

This is only viable for the PFS, since this is the most centralised instance in our protocol.
The PFS provides correct paths for initiators, possible presence problems after the path has been suggested has still to be considered between nodes along the path. 

A PR for this is in progress: #896

**Comment by karlb** [comment]
Closed by #896.
