### ISSUE TITLE
Observe presence inconsistencies and notify node

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-services#902]
## Abstract
Since #899 the PFS is connected to all matrix servers in a federation. Therefore it can detect inconsistencies of presences of a single user within the federation. As the presence can be repropagated through the federation by proactively setting a new presence through the API endpoint by any user, the PFS should have the ability to observe inconsistencies and notify the raiden node. 

Although #899 is a sufficient solution for a working PFS, it is desirable to have consistent presence in the whole federation as raiden nodes currently depend on the presences of their peers (they do not send messages if the peer is offline)

## technical solution
As discussed with @ulope and @andrevmatos, this could be done via a non-protocol toDevice message. It ensures backwards compatability as an older raiden node would simply ignore this message. The Raiden node should react to this message by setting the presence on its homeserver. 

Following things need to be determined yet 

- [ ] find a suitable time interval to give the federation the time to propagate (until the node is considered to have an inconsistent state). 
- [ ] find a suitable interval to renotify the node if it did not remove the inconsistency
- [ ] Think about if the PFS also submits the status message to the peer which then submits the presence with this status message
- [ ] handling race conditions if the node indeed goes offline (should the presence of the node's homeserver always be prioritized)?

**Comment by karlb** [comment]
I don't think we need this with the other workarounds in place. Does anyone disagree? Otherwise, I'll close this.
