### ISSUE TITLE
Listen to and process toDevice messages

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-services#914]
## Description

PFS needs to accept and process to_device messages by calling the respective handler. In order to be backwards compatible it should also call the handler on room messages. 

Additionally, the handler should be called on all clients. A Raiden node will send to_device messages to the local PFS `MXID`.

**Comment by ezdac** [comment]
>Additionally, the handler should be called on all clients. A Raiden node will send to_device messages to the local PFS MXID.

I'm not sure if I'm understanding correctly, but this is probably better to implement after #909 is finished?

**Comment by fredo** [comment]
The only thing we need to extend is passing the message handler to the other clients as well, once the PR is implemented
But you can also build on #909 if you like
