### ISSUE TITLE
PFS needs to do a full `initial_sync` on startup

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-services#948]
## Problem Definition

When using the `PresenceRoutingModule` from https://github.com/raiden-network/raiden-synapse-modules/pull/7/files the PFS will _only_  receive the full current presence state, if it does not re-use a previous sync-token.

This is part of https://github.com/raiden-network/raiden-service-bundle/issues/260

## Detailed description

The PFSPresenceRoutingModule schedules the full local presence state to be sent to the registered service users via
```
ModuleApi.send_local_online_presence_to
```

If the service user is not currently online, it will receive it when it does the next sync.
If the service user goes offline and comes online _again_, it needs to do the full initial sync to receive all current presence state again.

**Comment by karlb** [comment]
From what I can see, we don't save any sync tokens. Please reopen if you meant something else @konradkonrad.

**Comment by konradkonrad** [comment]
this is good then!
